// Product and category data for flustre

export const categories = [
  {
    name: "Living",
    image: "https://marketlube-ecommerce.s3.ap-south-1.amazonaws.com/Flustre/category/category1+(re).jpg",
  },
  {
    name: "Bedroom",
    image: "https://marketlube-ecommerce.s3.ap-south-1.amazonaws.com/Flustre/category/category2+(re).jpg",
  },
  {
    name: "Dining & Kitchen",
    image: "https://marketlube-ecommerce.s3.ap-south-1.amazonaws.com/Flustre/category/category3+(re).jpg",
  },
  {
    name: "Office",
    image: "https://marketlube-ecommerce.s3.ap-south-1.amazonaws.com/Flustre/category/category4+(re).jpg",
  },
  {
    name: "Outdoor",
    image: "https://marketlube-ecommerce.s3.ap-south-1.amazonaws.com/Flustre/category/category5+(re).jpg",
  },
];

export const bestSellers = [
  {
    id: 101,
    name: "Hydrating Face Wash",
    category: "Skin Care",
    price: "₹ 599",
    originalPrice: "₹ 799",
    image: "/skin1.jpg",
    badge: "#1",
  },
  {
    id: 102,
    name: "Nourishing Body Lotion",
    category: "Body & Shower",
    price: "₹ 349",
    originalPrice: "₹ 499",
    image: "/bodywah.jpg",
    badge: "#2",
  },
  {
    id: 103,
    name: "Herbal Anti-Dandruff Shampoo",
    category: "Hair Care",
    price: "₹ 299",
    originalPrice: "₹ 399",
    image: "/haircare1.jpg",
    badge: "#3",
  },
  {
    id: 104,
    name: "Long-Lasting Deodorant Roll-On",
    category: "Soap & Deodorants",
    price: "₹ 199",
    originalPrice: "₹ 249",
    image: "/soap.png",
  },
  {
    id: 105,
    name: "Vitamin C Brightening Serum",
    category: "Skin Care",
    price: "₹ 799",
    originalPrice: "₹ 999",
    image: "/skin2.jpg",
  },
  {
    id: 106,
    name: "Moisturizing Hair Conditioner",
    category: "Hair Care",
    price: "₹ 499",
    originalPrice: "₹ 699",
    image: "/haircare2.jpg",
  },
];

export const featuredProducts = [
  {
    id: 1,
    name: "Modern 3-Seater Sofa",
    category: "Sofas",
    rating: 4.7,
    description:
      "Plush 3-seater fabric sofa with solid wood frame, high-density foam, and ergonomic armrests. Perfect for contemporary living rooms.",
    price: "₹ 2,999",
    originalPrice: "₹ 3,499",
    image:
      "/featured/featured7.jpg",
  },
  {
    id: 2,
    name: "Luxury 2-Seater Sofa",
    category: "Sofas",
    rating: 4.5,
    description:
      "Elegant 2-seater sofa with leather upholstery, wood frame, and deep seat cushions. Ideal for formal living spaces.",
    price: "₹ 2,499",
    originalPrice: "₹ 3,199",
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/bestseller/8613516cf28a3fde364291c8bf09a4eb.jpg",
  },
];

// Full catalog used on /products page (exported for search suggestions)
export const catalogProducts = [
  // Hair Care products
  {
    id: "hc1",
    name: "Professional Hair Shampoo",
    type: "Hair Care",
    price: 899,
    originalPrice: 1099,
    image: "/haircare3.jpg",
    category: "Hair Care",
    discount: 18,
  },
  {
    id: "hc2",
    name: "Nourishing Hair Conditioner",
    type: "Hair Care",
    price: 799,
    originalPrice: 999,
    image: "/haircare2.jpg",
    category: "Hair Care",
    discount: 20,
  },
  {
    id: "hc3",
    name: "Anti-Dandruff Treatment",
    type: "Hair Care",
    price: 699,
    originalPrice: 899,
    image: "/haircare3.jpg",
    category: "Hair Care",
    discount: 22,
  },
  {
    id: "hc4",
    name: "Hair Growth Serum",
    type: "Hair Care",
    price: 1299,
    originalPrice: 1599,
    image: "/haircare2.jpg",
    category: "Hair Care",
    discount: 19,
  },
  // Soap & Deodorants products
  {
    id: "sd1",
    name: "Natural Handmade Soap",
    type: "Soap & Deodorants",
    price: 299,
    originalPrice: 399,
    image: "/soap1.jpeg",
    category: "Soap & Deodorants",
    discount: 25,
  },
  {
    id: "sd2",
    name: "Antibacterial Body Wash",
    type: "Soap & Deodorants",
    price: 449,
    originalPrice: 599,
    image: "/soap2.jpg",
    category: "Soap & Deodorants",
    discount: 25,
  },
  {
    id: "sd3",
    name: "Long-lasting Deodorant",
    type: "Soap & Deodorants",
    price: 199,
    originalPrice: 299,
    image: "/soap3.jpg",
    category: "Soap & Deodorants",
    discount: 33,
  },
  {
    id: "sd4",
    name: "Moisturizing Bath Soap",
    type: "Soap & Deodorants",
    price: 349,
    originalPrice: 449,
    image: "/soap1.jpeg",
    category: "Soap & Deodorants",
    discount: 22,
  },
  // Skin Care products
  {
    id: "sc1",
    name: "Hydrating Face Moisturizer",
    type: "Skin Care",
    price: 899,
    originalPrice: 1099,
    image: "/skin1.jpg",
    category: "Skin Care",
    discount: 18,
  },
  {
    id: "sc2",
    name: "Vitamin C Brightening Serum",
    type: "Skin Care",
    price: 1299,
    originalPrice: 1599,
    image: "/skin2.jpg",
    category: "Skin Care",
    discount: 19,
  },
  {
    id: "sc3",
    name: "Gentle Facial Cleanser",
    type: "Skin Care",
    price: 599,
    originalPrice: 799,
    image: "/skin3.jpg",
    category: "Skin Care",
    discount: 25,
  },
  {
    id: "sc4",
    name: "Anti-Aging Night Cream",
    type: "Skin Care",
    price: 1499,
    originalPrice: 1899,
    image: "/skin5.jpg",
    category: "Skin Care",
    discount: 21,
  },
  // Oral Care products
  {
    id: "oc1",
    name: "Whitening Toothpaste",
    type: "Oral Care",
    price: 199,
    originalPrice: 299,
    image: "/tooth1.jpg",
    category: "Oral Care",
    discount: 33,
  },
  {
    id: "oc2",
    name: "Electric Toothbrush",
    type: "Oral Care",
    price: 899,
    originalPrice: 1199,
    image: "/tooth2.jpg",
    category: "Oral Care",
    discount: 25,
  },
  {
    id: "oc3",
    name: "Mouthwash Fresh Mint",
    type: "Oral Care",
    price: 299,
    originalPrice: 399,
    image: "/tooth3.jpg",
    category: "Oral Care",
    discount: 25,
  },
  {
    id: "oc4",
    name: "Dental Floss Set",
    type: "Oral Care",
    price: 149,
    originalPrice: 249,
    image: "/tooth4.jpg",
    category: "Oral Care",
    discount: 40,
  },
  // Oral & Misc products (same as Oral Care but with different type)
  {
    id: "oc1_misc",
    name: "Whitening Toothpaste",
    type: "Oral & Misc",
    price: 199,
    originalPrice: 299,
    image: "/tooth1.jpg",
    category: "Oral & Misc",
    discount: 33,
  },
  {
    id: "oc2_misc",
    name: "Electric Toothbrush",
    type: "Oral & Misc",
    price: 899,
    originalPrice: 1199,
    image: "/tooth2.jpg",
    category: "Oral & Misc",
    discount: 25,
  },
  {
    id: "oc3_misc",
    name: "Mouthwash Fresh Mint",
    type: "Oral & Misc",
    price: 299,
    originalPrice: 399,
    image: "/tooth3.jpg",
    category: "Oral & Misc",
    discount: 25,
  },
  {
    id: "oc4_misc",
    name: "Dental Floss Set",
    type: "Oral & Misc",
    price: 149,
    originalPrice: 249,
    image: "/tooth4.jpg",
    category: "Oral & Misc",
    discount: 40,
  },
  // Original catalog products
  {
    id: "1",
    name: "Glow & Hydrate Face Serum",
    type: "Skincare",
    price: 899,
    originalPrice: 1099,
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/bestseller/JcZhBwKYsh.webp",
    category: "Skincare",
    discount: 18,
  },
  {
    id: "2",
    name: "Luxury Beauty Collection Set",
    type: "Beauty Essentials",
    price: 2499,
    originalPrice: 3199,
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/bestseller/8613516cf28a3fde364291c8bf09a4eb.jpg",
    category: "Beauty Essentials",
    discount: 22,
  },
  {
    id: "3",
    name: "Anti-Aging Night Cream",
    type: "Anti-Aging",
    price: 1299,
    originalPrice: 1599,
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/bestseller/JcZhBwKYsh.webp",
    category: "Anti-Aging",
    discount: 19,
  },
  {
    id: "4",
    name: "Vitamin C Brightening Serum",
    type: "Skincare",
    price: 799,
    originalPrice: 999,
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/bestseller/8613516cf28a3fde364291c8bf09a4eb.jpg",
    category: "Skincare",
    discount: 20,
  },
  {
    id: "5",
    name: "Hyaluronic Acid Moisturizer",
    type: "Skincare",
    price: 699,
    originalPrice: 899,
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/bestseller/JcZhBwKYsh.webp",
    category: "Skincare",
    discount: 22,
  },
  {
    id: "6",
    name: "Retinol Eye Cream",
    type: "Anti-Aging",
    price: 999,
    originalPrice: 1299,
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/bestseller/8613516cf28a3fde364291c8bf09a4eb.jpg",
    category: "Anti-Aging",
    discount: 23,
  },
  {
    id: "7",
    name: "Gentle Facial Cleanser",
    type: "Skincare",
    price: 599,
    originalPrice: 799,
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/bestseller/JcZhBwKYsh.webp",
    category: "Skincare",
    discount: 25,
  },
  {
    id: "8",
    name: "SPF 50 Sunscreen",
    type: "Skincare",
    price: 899,
    originalPrice: 1199,
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/bestseller/8613516cf28a3fde364291c8bf09a4eb.jpg",
    category: "Skincare",
    discount: 25,
  },
  // New Launches Products
  {
    id: "13",
    name: "The Answer Super Shampoo",
    type: "Hair Care",
    price: 1299,
    originalPrice: 1599,
    image: "/newlaunch1.jpg",
    category: "Hair Care",
    discount: 19,
  },
  {
    id: "14",
    name: "Newest Onion Protein Shampoo",
    type: "Hair Care",
    price: 899,
    originalPrice: 1199,
    image: "/newlaunch2.jpg",
    category: "Hair Care",
    discount: 25,
  },
  {
    id: "15",
    name: "Flakes Anti-Dandruff Shampoo",
    type: "Hair Care",
    price: 699,
    originalPrice: 899,
    image: "/newlaunch3.jpg",
    category: "Hair Care",
    discount: 22,
  },
  {
    id: "16",
    name: "Redken Anti-Dandruff Shampoo",
    type: "Hair Care",
    price: 1499,
    originalPrice: 1899,
    image: "/newlaunch4.jpeg",
    category: "Hair Care",
    discount: 21,
  },
  // EngineeredBy7Hz Products
  {
    id: "17",
    name: "Glow & Hydrate Face Serum",
    type: "Skincare",
    price: 899,
    originalPrice: 1099,
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/bestseller/JcZhBwKYsh.webp",
    category: "Skincare",
    discount: 18,
  },
  {
    id: "18",
    name: "Luxury Beauty Collection Set",
    type: "Beauty Essentials",
    price: 2499,
    originalPrice: 3199,
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/bestseller/8613516cf28a3fde364291c8bf09a4eb.jpg",
    category: "Beauty Essentials",
    discount: 22,
  },
  {
    id: "19",
    name: "Anti-Aging Night Cream",
    type: "Anti-Aging",
    price: 1299,
    originalPrice: 1599,
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/bestseller/JcZhBwKYsh.webp",
    category: "Anti-Aging",
    discount: 19,
  },
  // Best Sellers Products
  {
    id: "20",
    name: "Dove Nutritive Solutions",
    type: "Hair Care",
    price: 1099,
    originalPrice: 1299,
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/bestseller/8613516cf28a3fde364291c8bf09a4eb.jpg",
    category: "Hair Care",
    discount: 15,
  },
  {
    id: "21",
    name: "Lux Body Wash",
    type: "Body & Shower",
    price: 1099,
    originalPrice: 1299,
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/bestseller/JcZhBwKYsh.webp",
    category: "Body & Shower",
    discount: 15,
  },
  {
    id: "22",
    name: "Rexona / Sure Deo",
    type: "Soap & Deodorants",
    price: 1899,
    originalPrice: 2099,
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/bestseller/JcZhBwKYsh.webp",
    category: "Soap & Deodorants",
    discount: 10,
  },
  {
    id: "23",
    name: "Vaseline Body Lotion",
    type: "Skin Care",
    price: 1099,
    originalPrice: 1299,
    image:
      "https://marketlube-website-assets.s3.ap-south-1.amazonaws.com/Souqalmart/bestseller/8613516cf28a3fde364291c8bf09a4eb.jpg",
    category: "Skin Care",
    discount: 15,
  },
  // Additional Products Set 1
  {
    id: "24",
    name: "Professional Hair Shampoo",
    type: "Hair Care",
    price: 899,
    originalPrice: 1099,
    image: "/haircare3.jpg",
    category: "Hair Care",
    discount: 18,
  },
  {
    id: "25",
    name: "Natural Handmade Soap",
    type: "Soap & Deodorants",
    price: 299,
    originalPrice: 399,
    image: "/soap1.jpeg",
    category: "Soap & Deodorants",
    discount: 25,
  },
  {
    id: "26",
    name: "Hydrating Face Moisturizer",
    type: "Skin Care",
    price: 899,
    originalPrice: 1099,
    image: "/skin1.jpg",
    category: "Skin Care",
    discount: 18,
  },
  {
    id: "27",
    name: "Whitening Toothpaste",
    type: "Oral Care",
    price: 199,
    originalPrice: 299,
    image: "/tooth1.jpg",
    category: "Oral Care",
    discount: 33,
  },
  {
    id: "28",
    name: "Nourishing Hair Conditioner",
    type: "Hair Care",
    price: 799,
    originalPrice: 999,
    image: "/haircare2.jpg",
    category: "Hair Care",
    discount: 20,
  },
  {
    id: "29",
    name: "Antibacterial Body Wash",
    type: "Soap & Deodorants",
    price: 449,
    originalPrice: 599,
    image: "/soap2.jpg",
    category: "Soap & Deodorants",
    discount: 25,
  },
  {
    id: "30",
    name: "Vitamin C Brightening Serum",
    type: "Skin Care",
    price: 1299,
    originalPrice: 1599,
    image: "/skin2.jpg",
    category: "Skin Care",
    discount: 19,
  },
  {
    id: "31",
    name: "Electric Toothbrush",
    type: "Oral Care",
    price: 899,
    originalPrice: 1199,
    image: "/tooth2.jpg",
    category: "Oral Care",
    discount: 25,
  },
  // Additional Products Set 2
  {
    id: "32",
    name: "Anti-Dandruff Treatment",
    type: "Hair Care",
    price: 699,
    originalPrice: 899,
    image: "/haircare3.jpg",
    category: "Hair Care",
    discount: 22,
  },
  {
    id: "33",
    name: "Long-lasting Deodorant",
    type: "Soap & Deodorants",
    price: 199,
    originalPrice: 299,
    image: "/soap3.jpg",
    category: "Soap & Deodorants",
    discount: 33,
  },
  {
    id: "34",
    name: "Gentle Facial Cleanser",
    type: "Skin Care",
    price: 599,
    originalPrice: 799,
    image: "/skin3.jpg",
    category: "Skin Care",
    discount: 25,
  },
  {
    id: "35",
    name: "Mouthwash Fresh Mint",
    type: "Oral Care",
    price: 299,
    originalPrice: 399,
    image: "/tooth3.jpg",
    category: "Oral Care",
    discount: 25,
  },
  {
    id: "36",
    name: "Hair Growth Serum",
    type: "Hair Care",
    price: 1299,
    originalPrice: 1599,
    image: "/haircare2.jpg",
    category: "Hair Care",
    discount: 19,
  },
  {
    id: "37",
    name: "Moisturizing Bath Soap",
    type: "Soap & Deodorants",
    price: 349,
    originalPrice: 449,
    image: "/soap1.jpeg",
    category: "Soap & Deodorants",
    discount: 22,
  },
  {
    id: "38",
    name: "Anti-Aging Night Cream",
    type: "Skin Care",
    price: 1499,
    originalPrice: 1899,
    image: "/skin5.jpg",
    category: "Skin Care",
    discount: 21,
  },
  {
    id: "39",
    name: "Dental Floss Set",
    type: "Oral Care",
    price: 149,
    originalPrice: 249,
    image: "/tooth4.jpg",
    category: "Oral Care",
    discount: 40,
  },
];

export const serviceBenefits = [
  {
    icon: "/cash1.svg",
    titleKey: "Secured Payment",
    alt: "Secured Payment",
  },
  {
    icon: "/cash2.svg",
    titleKey: "Delivery",
    alt: "Delivery",
  },
  {
    icon: "/cash3.svg",
      titleKey: "24x7 Support",
    alt: "24x7 Support",
  },
  {
    icon: "/cash4.svg",
    titleKey: "Pay on Delivery",
    alt: "Pay on Delivery",
  },
];

export const navigationLinks = [
  "Hair Care",
  "Body & Shower",
  "Soap & Deodorants",
  "Skin Care",
  "Oral & Misc",
];
